import Head from 'next/head'
import HomeLayout from "@/layouts/home/homeLayout";
import {useEffect} from "react";
import CurrentSessionFetcher from "@/clientStateFetchers/impls/currentSessionFetcher";

export default function Home() {
    useEffect(() => {
        new CurrentSessionFetcher().fetch();
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeLayout title={"Feed"}>
                Testas
            </HomeLayout>
        </>
    )
}
